name = "TCIAlgorithms"
uuid = "baf62351-2e82-41dd-9129-4f5768a618e1"
authors = ["Hiroshi Shinaoka <h.shinaoka@gmail.com> and contributors"]
version = "0.4.3"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
EllipsisNotation = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
FastMPOContractions = "f6e391d2-8ffa-4d7a-98cd-7e70024481ca"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
TCIITensorConversion = "9f0aa9f4-9415-4e6a-8795-331ebf40aa04"
TensorCrossInterpolation = "b261b2ec-6378-4871-b32e-9173bb050604"

[compat]
EllipsisNotation = "1"
ITensors = "0.3"
OrderedCollections = "1"
QuanticsGrids = "0.3.1"
SpecialFunctions = "2"
TCIITensorConversion = "0.1.3"
TensorCrossInterpolation = "0.9.7"
julia = "1.6"

[extras]
QuanticsGrids = "634c7f73-3e90-4749-a1bd-001b8efc642d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random", "QuanticsGrids"]
